version: '3'
services:
  content_server:
    image: joaopio/content-server
    ports:
      - 4000:80
    environment:
      - NGINX_PORT=80
      - CONTENT_PATH=/wwwroot
      - CONTENT_AUTH_URL=http://content_authorizator
    volumes:
      - /home/www-data:/wwwroot
    networks:
      - content_network

  content_authorizator:
    image: joaopio/content-authorizator
    ports:
      - 5000:80
    environment:
      - API_PORT=80
    networks:
      - content_network
networks:
  content_network: