version: '3'
services:
  content_server:
    build: .
    ports:
      - "2222:22"
      - "4000:80"
    environment:
      - NGINX_PORT=80
      - CONTENT_PATH=/content
      - CONTENT_AUTH_URL=http://content_authorizator
      - USER_NAME=content
      - USER_PASSWORD=password
    volumes:
      - c:/content:/content
    networks:
      - content_network

  content_authorizator:
    image: joaopio/content-authorizator
    ports:
      - 5000:80
    environment:
      - API_PORT=80
    networks:
      - content_network
networks:
  content_network:
